stages:
    - build
    
building:
    stage: build
    script:
        - pip install --upgrade conan
        - mkdir build
        - cd build
        - cmake -DCPP_SCHEDULER_TESTS=TRUE ../
        - make
        - make test
