stages:
    - build
    - test
    
building:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ../
        - make
        
testing:
    stage: test
    script:
        - cd build
        - make test