dist: trusty
sudo: false
language: cpp

addons:
  sonarcloud:
    organization: "eaglegor-github"
    branches:
      - master
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

install:
  - mkdir -p latest-gcc-symlinks
  - ln -s /usr/bin/gcc-5 latest-gcc-symlinks/gcc
  - ln -s /usr/bin/g++-5 latest-gcc-symlinks/g++
  - export PATH=$PWD/latest-gcc-symlinks:$PATH
  
jobs:
  include:
    - stage: test
      compiler: 
        - gcc
      script: 
        - cd ..
        - mkdir SchedulerEngine-build
        - cd SchedulerEngine-build
        - cmake -DTHIRD_PARTY_DIRECTORY=$HOME/ThirdPartyLibs -DTHIRD_PARTY_PACKAGES_DIRECTORY=$HOME/ThirdPartyLibsPackages -DCPP_SCHEDULER_TESTS=True $TRAVIS_BUILD_DIR
        - make clean all
        - make test
    - compiler: 
        - clang
      script: 
        - cd ..
        - mkdir SchedulerEngine-build
        - cd SchedulerEngine-build
        - cmake -DTHIRD_PARTY_DIRECTORY=$HOME/ThirdPartyLibs -DTHIRD_PARTY_PACKAGES_DIRECTORY=$HOME/ThirdPartyLibsPackages -DCPP_SCHEDULER_TESTS=True $TRAVIS_BUILD_DIR
        - make clean all
        - make test
    - stage: static analysis
      branches:
        only:
          - master
      compiler:
        - clang
      script:
        - cd ..
        - mkdir SchedulerEngine-build
        - cd SchedulerEngine-build
        - cmake -DTHIRD_PARTY_DIRECTORY=$HOME/ThirdPartyLibs -DTHIRD_PARTY_PACKAGES_DIRECTORY=$HOME/ThirdPartyLibsPackages -DCPP_SCHEDULER_TESTS=True $TRAVIS_BUILD_DIR
        - build-wrapper-linux-x86-64 --out-dir bw-output make clean all 
        - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/ThirdPartyLibsPackages'
