dist: trusty
sudo: false
language: cpp

addons:
  sonarcloud:
    organization: "eaglegor-github"
    branches:
      - master
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:george-edison55/cmake-3.x'
    packages:
      - cmake
      - gcc-5
      - g++-5

install:
  - mkdir -p path-override
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz 
  - tar -xvzf cmake-3.4.1.tar.gz 
  - cd cmake-3.4.1/ 
  - ./configure --prefix=..
  - make install
  - cd ..
  - ln -s /usr/bin/gcc-5 latest-gcc-symlinks/gcc
  - ln -s /usr/bin/g++-5 latest-gcc-symlinks/g++
  - export PATH=$PWD/path-override:$PATH
  - cd ..
  
jobs:
  include:
    - stage: test
      compiler: 
        - gcc
      script: 
        - cd ..
        - mkdir SchedulerEngine-build
        - cd SchedulerEngine-build
        - cmake -DTHIRD_PARTY_DIRECTORY=$HOME/ThirdPartyLibs -DTHIRD_PARTY_PACKAGES_DIRECTORY=$HOME/ThirdPartyLibsPackages -DCPP_SCHEDULER_TESTS=True $TRAVIS_BUILD_DIR
        - make clean all
        - make test
    - compiler: 
        - clang
      script: 
        - cd ..
        - mkdir SchedulerEngine-build
        - cd SchedulerEngine-build
        - cmake -DTHIRD_PARTY_DIRECTORY=$HOME/ThirdPartyLibs -DTHIRD_PARTY_PACKAGES_DIRECTORY=$HOME/ThirdPartyLibsPackages -DCPP_SCHEDULER_TESTS=True $TRAVIS_BUILD_DIR
        - make clean all
        - make test
    - stage: static analysis
      branches:
        only:
          - master
      compiler:
        - clang
      script:
        - cd ..
        - mkdir SchedulerEngine-build
        - cd SchedulerEngine-build
        - cmake -DTHIRD_PARTY_DIRECTORY=$HOME/ThirdPartyLibs -DTHIRD_PARTY_PACKAGES_DIRECTORY=$HOME/ThirdPartyLibsPackages -DCPP_SCHEDULER_TESTS=True $TRAVIS_BUILD_DIR
        - build-wrapper-linux-x86-64 --out-dir bw-output make clean all 
        - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/ThirdPartyLibs'
    - '$HOME/ThirdPartyLibsPackages'
