dist: trusty
sudo: false
language: cpp

addons:
  sonarcloud:
    organization: "eaglegor-github"
    branches:
      - master
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:ppsspp/cmake'
    packages:
      - cmake
      - gcc-5
      - g++-5

install:
  - cd ..
  - mkdir -p path-override
  - ln -s /usr/bin/gcc-5 path-override/gcc
  - ln -s /usr/bin/g++-5 path-override/g++
  - ln -s /usr/bin/gcov-5 path-override/gcov
  - export PATH=$PWD/path-override:$PATH
  
env:
  global:
    - secure: "EhgL1ronzaNdloGRqlL6cY6FPXWtvdn+Ou5K/AyJu2qdNyNGgeKDI0ST2iW695e66IlU5kNeZJHIsT7+BW805uMG7QTrr5BEdBJPG/q6nqonk5bMz4qPStQkaGcttBRhs8FgiH1dBS0c74KxMeemtmzec59M4Xe06kPHqxy9DA3qA2728NaPc5eoXTeGwPkx83KgbmhEM93nGcu8/V65ITs88UW7gdRpicsYNlVTg3JZzPd2JBZYAQlSxvDi1xwa+nyS2c492NrDIHqY/Hfmb0xqzZUiymzNqxelfgXu8gtfCgYdtXs23V4Ni7YHXHkO+7RqbtYq9xeSlnipCh7em5J2KV3rb8ZT4qpaXjZds55MclbT6SxtnHyxMEEjMV6Wt9nq6tVa8lwaw5HDJ3vydis2VW3BVeeiegoSz3qMjDgO/wg8r4ED6+GoGM8sATIufgh1JB1V3agRApYlGsRDPYFjbQ1R17S0MwPn+/ZUzcZLsHEd4xKPM0IbsW7wnqzeANyq+wQGY4JiCiqLUsWlutX1V5STQKtU3eRtvxwJAgxn3DKbqI8gzAJJEjxoacOG3EN3aPS8H9RFbcqhhu+2PBTLQ8C+FCRNW/53Sswi5vPrg0jAAoD7aj6BYGnQqlKkdyqjslqgATZydDsKK+I20GC1xScBBgeJ2Or1ZEh8aBY="
    - secure: "d6S91I4IVUrS6p8NrYHz6MhUn4ADilwc6Nl/HjDdPyK59rPYihhwdKj0kdPMWTxBUPGKRwfAYb6qRL4clVjr0oWPWmfRGuLX83DWrNABQE6RRoIRV1ACBPfzeEqx0qdwEImvfSHBJMq7I8xbMn9iIp21PuiGMrXHWyK8CtRzV57GC+3fR5n73QCY/9ff+qqnJwWuiRXwBx1Z9E6iuMPLjgnsvaojPhiZHQAzvj6utZloFJjNqfvaspL3zdJVKz6ElVVInhDXcIUsSVy6r9bqhJCxCzb144tAorjaRPM6irVb6mnfOLcuA60lqY8g/MNFRXlnBWcw0HTVbLoJ27Kuim9gTieDxaVsPUAZzjzmgFh1Qp2OYcx+tCzZmwIv1KxcfuNMbdwWmCUgtMKB9rQy1++Vf+aNFpSX7DxbNEqyUpOwZhbLxQLO/vJomrtB8g5nYvwgowdexqcA3yDZ4DqrOEsziuEHZOGOzKvKKa03LEkZYbDLgzM3ciCMM9CvgBvpUPREYHbQ0+8ALlMI+lOm45J0N1EoePBquovnIe+l4Z8XwUg1Plsh6TxBN/k14Bi/2qykverYE8+cskDVmbTgCzvSOIOCJxKm+hh0MCNviUCt6fuhLQSGOlxUyB37z4/S+aN4+QgANRIHMBkaNTnMskag2t6LB9Lqdzq+CaJ4hxI="

jobs:
  include:
    - stage: test
      compiler: 
        - gcc
      script: 
        - mkdir SchedulerEngine-build
        - cd SchedulerEngine-build
        - cmake -DCMAKE_BUILD_TYPE=Coverage -DTHIRD_PARTY_DIRECTORY=$HOME/ThirdPartyLibs -DTHIRD_PARTY_PACKAGES_DIRECTORY=$HOME/ThirdPartyLibsPackages -DCPP_SCHEDULER_TESTS=True $TRAVIS_BUILD_DIR
        - build-wrapper-linux-x86-64 --out-dir bw-output make -j2 clean all test coverage
        - cd ../SchedulerEngine
        - cp ../SchedulerEngine-build/*.gcov .
        - export SONAR_SCANNER_OPTS="-Xmx512m"
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export SONAR_ADDITIONAL_OPTS="-Dsonar.analysis.mode=preview -Dsonar.github.oauth=$MAINTAINANCE_TOKEN -Dsonar.github.repository=Eaglegor/SchedulerEngine -Dsonar.github.pullRequest=$TRAVIS_PULL_REQUEST" ; fi
        - sonar-scanner $SONAR_ADDITIONAL_OPTS -Dsonar.projectKey=scheduler-engine -Dsonar.projectVersion=0.1 -Dsonar.cfamily.build-wrapper-output=../SchedulerEngine-build/bw-output -Dsonar.cfamily.gcov.reportsPath=. -Dsonar.sources=. -Dsonar.projectName="Scheduler Engine"
    - compiler: 
        - clang
      script: 
        - mkdir SchedulerEngine-build
        - cd SchedulerEngine-build
        - cmake -DTHIRD_PARTY_DIRECTORY=$HOME/ThirdPartyLibs -DTHIRD_PARTY_PACKAGES_DIRECTORY=$HOME/ThirdPartyLibsPackages -DCPP_SCHEDULER_TESTS=True $TRAVIS_BUILD_DIR
        - make -j2 clean all test

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/ThirdPartyLibs'
    - '$HOME/ThirdPartyLibsPackages'
