dist: trusty
sudo: false
language: cpp

addons:
  sonarcloud:
    organization: "eaglegor-github"
    token:
      secure: 'TyHSTW9Yp8yGp2ikfFoMIABdNTdk6zunttdJGHvMP8sFW4zzF1LVMyIN+FN03APsLWix2A9IQt1KbVZn2UYqYR6RY5XfenLE3heoF2j2yHlP+K/pvx38/L+vAsELET+jegp7Uo3t1Hb95PR6pbzgMFHOq5/RAcifb9pQWGrEYZJS7zx7+iyltz6inlLllE9RCmBDDky2bFxzxZP+3WkjHOPmkOwfe/4/WsZtMPdqK5DnysM/WGJnjdzhKDc2oJymGaj9Kz2vzJKD+eFGb9ALK4EzVx2jautcgWoQH4dUeGnlEEJUifFBGOQiIRRzkRt2Pkml2IY6j1pSGVkF9RWJaJKoo959blnwP07TX7y6hWDzC5iC7j96mPpS4TpwhN1ttTeHEa2F7Ae4hbN+qPSxXiBOxcJCEV0lTkjLexxYvOC7ma1cfALMqyp2DEKdeYg9xGmasbCQt4pTd44Ji9ye3S3lDTw2cL9J1vcDQOtWHtorVA2bq03uxX2lvDpr3bMpTV3SpSKTGDZfEu8TmnFY1Q+nn4glggL8VS6iwsuIFGs6IigTeiS3RFkjM+FNeXkQVpuMJB5NZdjJQUUuiOOL2mpbL2FzwVX7C242fubPocsS79XZP5/wSkdhSBUcdaEVZA7NOhYf6D3IFAKxrC1GuIpzCPvZF2BefgNCIGSXFY8='
    github_token:
      secure: 'LladLSKJVETzqPgIKNgd1CcxwCeMD979FxWypEtj26bPYm/7d8A/L3M7JsYhz1JxVyW59MYYaUu+n5xwYjvLfrESDNSZ8DhtwZ80tfZtDv6nIzEzVPJmmJ9BoPEev0z4RJ6DJu969Opn/fswWOJ+NsatDjgv16WxxvJbRbORL9TMOij6E08udPNpnEIHSYC6bOwWmJrpJ5mfvTxik4/evHECPU10rTVodQMgopOJ4jtvQUXgGk3vxHHKORx2SpuoudQbPibLcmRpXr5+FDMO7Icl67baS/jDfb+0ZR6gT6B9BnPiW4QcAuJvaTpATFw7exlVfTcE74KmvarL5xYpgA0hyYVtoVV88ZmPx81MaYkWzJC1cV2s0gvIkDe8lfUDa3DpCdRZkpiuNteIC0waMmF5VSBV5Oj7h3Zphlfc4RL8O+zKCAd/inlcuAPmEI8Z2BZDVvdmjsG+U3QlpVLDYJzLNC7c/8Dff5ozX1Jbwzx5PoqUM4Js8ING6wUOWqTXzjq0EISfsz/B/HrgWicVrlZOwwgZRUWd53p8vHGE22YgbpKfndYVn/2G1NEaV5v7DjiawgGOKuLB7Vtp1y1X01cSEssyiSuBXj0CBSPP5TdgJeKBy3PuPsvVuYm0z4QBosaFVTUO7AwEpFAjCzP3P8zRFWAYJ3qouafJID+X0qc='
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:ppsspp/cmake'
    packages:
      - cmake
      - gcc-5
      - g++-5
      - doxygen
      - graphviz

install:
  - cd ..
  - mkdir -p path-override
  - ln -s /usr/bin/gcc-5 path-override/gcc
  - ln -s /usr/bin/g++-5 path-override/g++
  - ln -s /usr/bin/gcov-5 path-override/gcov
  - export PATH=$PWD/path-override:$PATH
  
- env:		
   - global:		
      - secure: "T4cgwzy8KsvxXAgbTZp+VTSdrcjk3UyBZ34mGUpPY/WkPPugvc0rQnfNts6SrGf/0PM+0ASXAJgpAaHBXM4UjkZ8klhyJoo+KKE+l+1vIz4WKSwo0Got2CLdW+HssV2qTW3oAeMvioKlL45K8PyIF21/3wexypTHA53cPrYfCfKD3SKGkwsGvjDzK6QlgVq2SD7PFengeK6gkIkbogkBGrOwAX0CXm9DYZAl50JAY9AwbVaqeRsWh4xFjD5guaU7sEyEcXATGQd5YO2VMHI4BdjIhyT/Zr5MIcD0Q87EnD0KfCBzEpvqzlXddZOcKZPvtCFnb+6a6+duX6WiuSfQa+iJxDEPVOC+LtHuxB65Vz5oNrO6urONIJqw7UlKfhbUX8MlhzBVMxjMPou9/lTXFJf6/jn/uSYpFMEcWztKX5UN2rjL/P2WhMCqaZDprCuIjAemvZuLJswSwg1dtIgekhQiOVTBClJd0NSEq4D8h0xcKlP6EYm7eqFWrwebx0XNMLIUUrylP2q25dBIKIsuyxoMTTofAxWYCBxAFzCtBO2FBZk9DCD7RnGl9pvk6Y7DuV0dRalG3fvhUwwWNIpZeWbfn4fCPVcFopw4GZ/0X+RmtYxvoSRV9Y3zxyaU2hzEsU1cOMzVPjH0/uszdynv8+EXKHosJKDCTDVoL0dghEY="
  
jobs:
  include:
    - stage: test
      compiler: 
        - gcc
      script: 
        - mkdir SchedulerEngine-build
        - cd SchedulerEngine-build
        - cmake -DCMAKE_BUILD_TYPE=Coverage -DTHIRD_PARTY_DIRECTORY=$HOME/ThirdPartyLibs -DTHIRD_PARTY_PACKAGES_DIRECTORY=$HOME/ThirdPartyLibsPackages -DCPP_SCHEDULER_TESTS=True $TRAVIS_BUILD_DIR
        - build-wrapper-linux-x86-64 --out-dir bw-output make -j2 clean all test coverage
        - cd ../SchedulerEngine
        - cp ../SchedulerEngine-build/*.gcov .
        - export SONAR_SCANNER_OPTS="-Xmx512m"
        - sonar-scanner -Dsonar.projectKey=scheduler-engine -Dsonar.projectVersion=0.1 -Dsonar.cfamily.build-wrapper-output=../SchedulerEngine-build/bw-output -Dsonar.cfamily.gcov.reportsPath=. -Dsonar.sources=. -Dsonar.projectName="Scheduler Engine"
    - compiler: 
        - clang
      script: 
        - mkdir SchedulerEngine-build
        - cd SchedulerEngine-build
        - cmake -DTHIRD_PARTY_DIRECTORY=$HOME/ThirdPartyLibs -DTHIRD_PARTY_PACKAGES_DIRECTORY=$HOME/ThirdPartyLibsPackages -DCPP_SCHEDULER_TESTS=True $TRAVIS_BUILD_DIR
        - make -j2 clean all test
    - stage: generating docs
      script: 
        - >
          if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
            cd SchedulerEngine
            echo "Generating doxygen docs"
            git clone -b gh-pages https://${MAINTAINANCE_TOKEN}@github.com/Eaglegor/SchedulerEngineDocs.git docs
            rm -rf docs/*
            
            git config --global push.default simple
            git config user.name "Eaglegor"
            git config user.email "eaglegor@gmail.com"
            
            echo "" > docs/.nojekyll
            doxygen
            cd docs
            if [ -f "index.html" ]; then
              git add --all
              git commit -m "Updating documentation from commit {$TRAVIS_COMMIT}"
              git push "https://${MAINTAINANCE_TOKEN}@github.com/Eaglegor/SchedulerEngineDocs.git"
            fi
          fi


cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/ThirdPartyLibs'
    - '$HOME/ThirdPartyLibsPackages'
